name: Feature Request
description: Suggest features for QuickBench, or just ask for an update.

labels: [ 'enhancement' ]

body:
  - type: textarea
    attributes:
      label: What would you like added or changed?
      placeholder: A clear and concise description of what you'd like.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Any additional context or solutions you thought of?
    validations:
      required: false
