name: Publish release

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v3
      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Build and publish with Gradle
        run: ./gradlew build modrinth curseforge --continue --no-daemon
        env:
          BUILD_RELEASE: ${{github.event.prelease == false}}
          MODRINTH_TOKEN: ${{secrets.MODRINTH}}
          CURSEFORGE_TOKEN: ${{secrets.CURSEFORGE}}
          CHANGELOG: ${{ github.event.release.body }}
      - name: Upload build artifacts
        if: always()
        uses: AButler/upload-release-assets@v3.0
        with:
          files: 'build/libs/*'
          repo-token: ${{secrets.GITHUB_TOKEN}}
